-- V1__create_books_table.sql

CREATE TABLE books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    isbn VARCHAR(50) NOT NULL,
    published_date DATE NOT NULL,
    price NUMERIC(12,2) NOT NULL,
    book_type VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO books (title, author, isbn, published_date, price, book_type) VALUES
('The Great Gatsby', 'F. Scott Fitzgerald', '9780743273565', '1925-04-10', 120.00, 'HARD_COVER'),
('To Kill a Mockingbird', 'Harper Lee', '9780061120084', '1960-07-11', 150.00, 'SOFT_COVER'),
('1984', 'George Orwell', '9780451524935', '1949-06-08', 100.00, 'EBOOK'),
('Pride and Prejudice', 'Jane Austen', '9780141439518', '1813-01-28', 90.00, 'SOFT_COVER'),
('The Catcher in the Rye', 'J.D. Salinger', '9780316769480', '1951-07-16', 110.00, 'HARD_COVER'),
('The Hobbit', 'J.R.R. Tolkien', '9780547928227', '1937-09-21', 200.00, 'HARD_COVER'),
('Fahrenheit 451', 'Ray Bradbury', '9781451673319', '1953-10-19', 95.00, 'EBOOK'),
('Brave New World', 'Aldous Huxley', '9780060850524', '1932-01-01', 105.00, 'AUDIOBOOK'),
('The Lord of the Rings', 'J.R.R. Tolkien', '9780618640157', '1954-07-29', 250.00, 'HARD_COVER'),
('Jane Eyre', 'Charlotte Brontë', '9780141441146', '1847-10-16', 85.00, 'SOFT_COVER'),
('Animal Farm', 'George Orwell', '9780451526342', '1945-08-17', 80.00, 'EBOOK'),
('Gone with the Wind', 'Margaret Mitchell', '9781451635621', '1936-06-30', 130.00, 'HARD_COVER'),
('The Alchemist', 'Paulo Coelho', '9780061122415', '1988-01-01', 140.00, 'SOFT_COVER'),
('The Da Vinci Code', 'Dan Brown', '9780307474278', '2003-03-18', 160.00, 'HARD_COVER'),
('Harry Potter and the Sorcerer''s Stone', 'J.K. Rowling', '9780590353427', '1997-06-26', 180.00, 'HARD_COVER');
